### PR TITLE
Not calling get revisions multiple times

### PR DESCRIPTION
**Pull request by sukritsangvong**
Change the code a bit to not call getRevisions multiple times just to get a date to display + a bunch of formatting

### CODE REVIEW

**Review by ducndh — COMMENTED** [review]
Change on my part looks fine

**Review by LuisaE — APPROVED** [review]
Thanks for fixing the formatting! Which Prettier settings are you using so I can copy?

**Comment by sukritsangvong** [comment]
@LuisaE i think most of the prettier conflicts came from duc's pr. my setting doesn't do anything to ur pr.

**Comment by LuisaE** [comment]
> @LuisaE i think most of the prettier conflicts came from duc's pr. my setting doesn't do anything to ur pr.

I know, just wanted to keep the same for consistency

**Pull request merged**
