### PR TITLE
Change organization of buttons

### PR DESCRIPTION
**Pull request by sukritsangvong**
Tried to make all the buttons more intuitive. I asked people around and they seemed to be unsure about what the highlight and the revision buttons do, so I made this PR to address those problems. 

Let me know if you agree to these changes / how they should be changed.

image

### CODE REVIEW

**Review by LuisaE — CHANGES_REQUESTED** [review]
I don't like it, something about big buttons bothers me. Let's discuss this at Tuesday's meeting. Blocking it for now, but if people disagree whatever

**Comment by sukritsangvong** [comment]
@LuisaE Yup sounds good. Big buttons bother me a little bit as well. But have to try to balance with people that don't know what "Highlight" is highlighting and what version of "Revision Page" are they going to. This is hard 🥲

**Review by LuisaE — APPROVED** [review]
Going with the crowd :) haha

**Comment by sukritsangvong** [comment]
Will make further changes in futre PRs

**Pull request merged**
